config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :favors do
    collection do 
    end
  end

  resources :fields
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  resources :layouts
  resources :sections
  root to: 'static#hello'

  get 'fields_preferences', to: 'static#choose_favors'
  get 'industries_preferences', to: 'static#choose_industries'
  get 'ratings', to: 'static#ratings'



 #  devise_scope :user do
 #  	delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
	# end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	has_many :identities
  has_many :layouts
  belongs_to :field
  has_many :favors
  has_many :sections, through: :favors
  has_many :fields, through: :favors
  has_many :comments
  
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]


def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    if user.save(:validate => false)

    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name
    user.image = auth.info.image
    # user.name = auth.info.name   # assuming the user model has a name
    # user.image = auth.info.image # assuming the user model has an image
  else
    redirect_to root_path
  end
  end
end

def man?
  self.uid == '1339708379392267'
end

def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  	before_action :set_user, only: [:show, :edit, :update]


	def show
		@avatar = @user.image+'?type=large'
		@articles = @user.layouts.reverse
		@sections = @user.sections.uniq
		@fields = @user.fields.uniq
	end

	def edit
		@avatar = @user.image+'?type=large'
	end

	def index
		@users = User.all
		
	end


	def update
		@avatar = @user.image+'?type=large'
		@user.update(user_params)

		respond_to do |format|
			if @user.save(:validate => false)
					if @user.sign_in_count == 1
						format.html { redirect_to fields_preferences_path, notice: 'Выберите сферы.' }
					else
						format.html { redirect_to @user, notice: 'Инфо обновлена.' }
						format.json { render :show, status: :ok, location: @user }
					end
				else
					format.html { render :edit }
					format.json { render json: @user.errors, status: :unprocessable_entity }
			end
		end
	end

	private

	def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :user_work_history, :about, :image, :job_name, :sign_in_count)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.slim
.col-md-3
	.user_card_wrap
		.user_card_avatar
			- avatar = user.image + '?type=large'
			= link_to(image_tag( avatar, class: "avatar_card"), user)
		.user_card_name
			= user.name
		.user_card_job
			- if user.user_work_history == nil
				| Эксперт 
			- else
				= user.user_work_history + ""
				|   из 
				= user.job_name
		/ .rating_field_name
		/ 	ul
		/ 		li.icon
		/ 			= image_tag("manager.png", class: "rating_icon") 
		/ 		li.percentage
		/ 			= user.layouts.map {|l| l.section.name }.select {|s| s == "Менеджмент"}.length

		/ 		li.icon
		/ 			= image_tag("startup.png", class: "rating_icon") 
		/ 		li.percentage
		/ 			= user.layouts.map {|l| l.section.name }.select {|s| s == "Стартапы"}.length

		/ 		li.icon
		/ 			= image_tag("finance.png", class: "rating_icon") 
		/ 		li.percentage
		/ 			= user.layouts.map {|l| l.section.name }.select {|s| s == "Финансы"}.length
					
		/ 		li.icon
		/ 			= image_tag("digital.png", class: "rating_icon") 
		/ 		li.percentage
		/ 			= user.layouts.map {|l| l.section.name }.select {|s| s == "Маркетинг"}.length
		/ 			= link_to ">>", "#", class: 'more'

app/views/users/edit.html.slim
.big_wrap
	.container
		.row
			.col-md-12
				.edit_heading
					| #{@user.name.split.first}, чем вы занимаетесь?
				.edit_profile
					= image_tag(@avatar, class: "big_avatar")

					.user_name_big.black
						= @user.name

					.edit_form_wrap
						= simple_form_for @user, html: { class: 'form-horizontal'  } do |f|
							
							.input
								= f.input :user_work_history, label: false, placeholder: 'Должность...', :input_html => { class: 'input-profession' }
							.input
								= f.input :job_name, label: false, placeholder: 'Название компании...', :input_html => { class: 'input-profession' }
							
							= f.button :submit, "Сохранить", class: "btn btn-default", id: "trigger"

app/views/users/index.html.slim
.big_wrap.white
	.users_wrap
		.container
			.row
				.col-md-12
					.latest_updates.profile
						| Все пользователи:
					
					.small_sections_wrap.main_page
						= render @users

app/views/users/show.html.slim
.row
	.col-md-12
		.user_info_wrap
			= image_tag(@avatar, class: "big_avatar")
				
			- if @user == current_user
				.profile_edit
					= link_to(image_tag("edit_white.png", class: "edit_icon"), edit_user_path(@user))

			.user_name_big
				= @user.name
			
			.user_job_big
				- if @user.user_work_history == nil
					| Эксперт 
				- else
					= @user.user_work_history + ""
					|   из 
					= @user.job_name

			.rating_wrap
				ul
					li
						.rating_field_name
							ul
								li.icon
									= image_tag("manager.png", class: "rating_icon") 
								li.percentage
									= @user.layouts.map {|l| l.section.name }.select {|s| s == "Менеджмент"}.length

								li.icon
									= image_tag("startup.png", class: "rating_icon") 
								li.percentage
									= @user.layouts.map {|l| l.section.name }.select {|s| s == "Стартапы"}.length

								li.icon
									= image_tag("finance.png", class: "rating_icon") 
								li.percentage
									= @user.layouts.map {|l| l.section.name }.select {|s| s == "Финансы"}.length
									
								li.icon
									= image_tag("digital.png", class: "rating_icon") 
								li.percentage
									= @user.layouts.map {|l| l.section.name }.select {|s| s == "Маркетинг"}.length
									= link_to ">>", ratings_path, class: 'more'
									
.container
	- if @user == current_user
		.row
			.col-md-12
				.layouts_group
						.button_add_layout
							= link_to "Поделиться знанием", new_layout_path, class: 'btn btn-default'
	.row
		.col-md-12
			.latest_updates.profile
				| #{@user.name} написал:
			
			.small_sections_wrap.main_page
				= render @articles, partial: "sections/child_section"

	- unless @sections.empty? && @user != current_user
		.row
			.col-md-12
				.latest_updates.profile.plates
					| #{@user.name} интересуется сферами:
					- if @user == current_user
						= link_to(image_tag("edit.png", class: "edit_icon"), fields_preferences_path)
				.sections_wrap
					= render @sections

	- unless @fields.empty? && @user != current_user
		.row
			.col-md-12
				.latest_updates.profile.plates
					| #{@user.name} интересуется отраслями:
					- if @user == current_user
						= link_to(image_tag("edit.png", class: "edit_icon"), industries_preferences_path)
				.sections_wrap
					= render @fields, partial: "sections/parent_section"