config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :favors do
    collection do 
    end
  end

  resources :fields
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  resources :layouts
  resources :sections
  root to: 'static#hello'

  get 'fields_preferences', to: 'static#choose_favors'
  get 'industries_preferences', to: 'static#choose_industries'
  get 'ratings', to: 'static#ratings'



 #  devise_scope :user do
 #  	delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
	# end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/section.rb
class Section < ApplicationRecord
	belongs_to :parent_section, :class_name => "Section", :foreign_key => "parent_section_id"
  	has_many :child_sections, :class_name => "Section", :foreign_key => "parent_section_id"
  	has_many :layouts
  	has_many :favors
	has_many :users
  	
  	
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    @layouts = Layout.where(section_id: @section.id)
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save(validate: false)
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :parent_section_id, :description)
    end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_child_section.html.slim
.child_section.name
	= link_to section.name, section

app/views/sections/_form.html.erb
<br>
<br>
<%= simple_form_for(@section) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :parent_section_id %>
    <%= f.input :description %>
    
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <br>
<br>
<br>
<br>
<% end %>

app/views/sections/_section.html.slim
.col-md-4
	.section_main_wrap
		.section_image_wrap
			- if section.id < 50
				= link_to (image_tag "#{section.id}.jpeg", class: "section_image"), section
			- else
				= link_to (image_tag "0.png", class: "section_image"), section
		.section_name
			= link_to (section.name), section
	
	/ - unless section.child_sections.empty?
	/ 	.child_wrap
	/ 		- section.child_sections.each do |s|
	/ 			.child_section_name
	/ 				= render partial: "sections/child_section", locals: {section: s}	
	/ 			

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.slim
.container
  .row
    .col-md-12
      .latest_updates.fields
        = link_to "Все сферы", "#"

      .sections_wrap
        = render @sections
        - if @able.call
          br
            = link_to 'Добавить сферу', new_section_path, class: 'btn'

app/views/sections/new.html.erb
<% if @able.call %>
<div class="container">
<div class="row">
<div class="col-md-6">

<br>
<br>

<h1>Новая сфера</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>



</div>
</div>
</div>
<br>
<br>
<br>
<br>
<% end%>

app/views/sections/show.html.slim
.big_wrap.white
	.row
		.col-md-12
			.header_wrap_small
				.text_wrap
					.back_wrap
						- if @section.parent_section.nil?
							= link_to image_tag('back_icon.png', class: "back_icon") + "Ко всем сферам", sections_path
						- else
							= link_to image_tag('back_icon.png', class: "back_icon") + @section.parent_section.name, section_path(@section.parent_section)

					.section_header_title
						= @section.name
				

	.container
		.row
			.col-md-12
				- if @section.child_sections.empty?
					.layouts_group
						.button_add_layout
							= link_to "Поделиться знанием", new_layout_path({:section_id => @section.id}), class: 'btn btn-default', method: :get

					.layouts_grid
						= render @layouts


				-else
					.small_sections_wrap
						= render @section.child_sections, partial: "sections/child_section"

					.row
						.col-md-12

							.layouts_grid
								= render @layouts