config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :favors do
    collection do 
    end
  end

  resources :fields
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  resources :layouts
  resources :sections
  root to: 'static#hello'

  get 'fields_preferences', to: 'static#choose_favors'
  get 'industries_preferences', to: 'static#choose_industries'
  get 'ratings', to: 'static#ratings'



 #  devise_scope :user do
 #  	delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
	# end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/field.rb
class Field < ApplicationRecord
	has_many :favors
	has_many :users
	has_many :layouts
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :set_field, only: [:edit, :update, :destroy]

  # GET /fields
  # GET /fields.json
  def index
    @fields = Field.all
  end

  # GET /fields/1
  # GET /fields/1.json
  def show
    @section = Field.find(params[:id])
    @layouts = @section.layouts
  end

  # GET /fields/new
  def new
    @field = Field.new
  end

  # GET /fields/1/edit
  def edit
  end

  # POST /fields
  # POST /fields.json
  def create
    @field = Field.new(field_params)

    respond_to do |format|
      if @field.save
        format.html { redirect_to @field, notice: 'Field was successfully created.' }
        format.json { render :show, status: :created, location: @field }
      else
        format.html { render :new }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fields/1
  # PATCH/PUT /fields/1.json
  def update
    respond_to do |format|
      if @field.update(field_params)
        format.html { redirect_to @field, notice: 'Field was successfully updated.' }
        format.json { render :show, status: :ok, location: @field }
      else
        format.html { render :edit }
        format.json { render json: @field.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fields/1
  # DELETE /fields/1.json
  def destroy
    @field.destroy
    respond_to do |format|
      format.html { redirect_to fields_url, notice: 'Field was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_field
      @field = Field.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def field_params
      params.require(:field).permit(:name, :image, :description)
    end
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/views/fields/_field.html.slim
.col-md-4
	.section_main_wrap
		.section_image_wrap			
			= link_to (image_tag "#{field.name}.jpeg", class: "section_image"), field
		.section_name
			= link_to (field.name), field
	
				

app/views/fields/_form.html.erb
<%= simple_form_for(@field) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :image %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<div class="container">
<div class="row">
<div class="col-md-12">

<h1>Редактировать отрасль</h1>

<%= render 'form', field: @field %>

<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

</div>
</div>
</div>

app/views/fields/index.html.slim
.container
  .row
    .col-md-12
      .latest_updates.fields
        = link_to "Все индустрии", "#"

      .sections_wrap
        = render @fields
      
      - if @able.call
        .stripped
          br
            = link_to 'Добавить индустрию', new_field_path, class: 'btn'

app/views/fields/new.html.erb
<% if @able.call %>
<div class="container">
<div class="row">
<div class="col-md-6">
<br>
<br>
<br>
<br>

<h1>Новая отрасль</h1>

<%= render 'form', field: @field %>

<%= link_to 'Back', fields_path %>


</div>
</div>
</div>
<br>
<br>
<br>
<br>
<% end%>

app/views/fields/show.html.slim
.big_wrap.white
	.row
		.col-md-12
			.header_wrap_small
				.text_wrap
					.back_wrap
						= link_to image_tag('back_icon.png', class: "back_icon") + "Ко всем индустриям", root_path

					.section_header_title
						= @section.name
				

	.container
		.row
			.col-md-12
				
				.layouts_group
					.button_add_layout
						= link_to "Поделиться знанием", new_layout_path({:section_id => @section.id}), class: 'btn btn-default', method: :get

				.layouts_grid
					= render @layouts