config/routes.rb
Rails.application.routes.draw do

  resources :comments
  resources :favors do
    collection do 
    end
  end

  resources :fields
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users
  resources :layouts
  resources :sections
  root to: 'static#hello'

  get 'fields_preferences', to: 'static#choose_favors'
  get 'industries_preferences', to: 'static#choose_industries'
  get 'ratings', to: 'static#ratings'



 #  devise_scope :user do
 #  	delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
	# end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/layout.rb
class Layout < ApplicationRecord
	belongs_to :section
	belongs_to :field
	belongs_to :user
  	has_many :comments
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  before_action :set_layout, only: [:show, :edit, :update, :destroy]

  # GET /layouts
  # GET /layouts.json
  def index
    @layouts = Layout.all
  end

  # GET /layouts/1
  # GET /layouts/1.json
  def show
    @comment = Comment.new
    @avatar = @layout.user.image+'?type=large'
    prepare_meta_tags(title: @layout.name,
                      description: @layout.description,
                      keywords: @layout.heading,
                      image: @avatar,
                      twitter: {card: "summary_large_image"})
  end

  # GET /layouts/new
  def new
    @layout = Layout.new
  end

  # GET /layouts/1/edit
  def edit
  end

  # POST /layouts
  # POST /layouts.json
  def create
    # @layout = Layout.new(layout_params)
    @layout = current_user.layouts.create(layout_params)

    respond_to do |format|
      if @layout.save
        format.html { redirect_to @layout, notice: 'Шаблон создан.' }
        format.json { render :show, status: :created, location: @layout }
      else
        format.html { render :new, :flash => { :error => "Oh no!" } }
        format.json { render json: @layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layouts/1
  # PATCH/PUT /layouts/1.json
  def update
    @layout.update(layout_params)
    respond_to do |format|
      if @layout.save(:validate => false)
        format.html { redirect_to @layout, notice: 'Layout was successfully updated.' }
        format.json { render :show, status: :ok, location: @layout }
      else
        format.html { render :edit }
        format.json { render json: @layout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layouts/1
  # DELETE /layouts/1.json
  def destroy
    @layout.destroy
    respond_to do |format|
      format.html { redirect_to layouts_url, notice: 'Layout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layout
      @layout = Layout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layout_params
      params.require(:layout).permit(:user_id, :heading, :section_id, :field_id,  :name, :description, :image_url, :content)
    end
end

app/helpers/layouts_helper.rb
module LayoutsHelper
end

app/views/layouts/_footer.html.slim
/ .navbar-fixed-bottom
/ 	.navbar-inner
.footer
	= link_to(image_tag("logo.png", class: "footer_logo"), root_path)
	.motto
		| Новые знания каждый день
	.rules
		ul
			li = link_to "Правила пользования", '#'
			li = link_to "Безопасность данных", '#'
	.rights
		| © 2016 Mindy

	

app/views/layouts/_form.html.erb
<%= form_for(layout) do |f| %>
  <% if layout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(layout.errors.count, "error") %> prohibited this layout from being saved:</h2>

      <ul>
      <% layout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/_google_analytics.html.slim
- if Rails.env.production?
	javascript:
		(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

		ga('create', 'UA-83039857-1', 'auto');
		ga('send', 'pageview');

app/views/layouts/_layout.html.slim
.col-md-4

	/ .time_posted
	/ 	= time_ago_in_words(layout.created_at) + ' назад' 
	.layout_card_wrap
		.avatar-wrap
			= link_to(image_tag(layout.user.image, class: "avatar"), current_user)
		.author__description
			.author__name
				= link_to layout.user.name, layout.user
			.author__work
				- if layout.user.user_work_history == nil
					| Эксперт 
				- else
					= layout.user.user_work_history
			/ .time_posted
			/ 	= time_ago_in_words(layout.created_at) + ' назад' 

		.layout_card_name
			= link_to layout.name, layout

		.time_posted
			= time_ago_in_words(layout.created_at) + ' ago' 
			
		.layout_card_description
			= truncate("#{layout.description}", length: 500, omission: '...')
			= link_to "  читать >", layout, class: "more_link"

app/views/layouts/_top_menu.html.slim
nav.navbar.navbar-default
  .container-fluid
    /! Brand and toggle get grouped for better mobile display
    .navbar-header
      	button.navbar-toggle.collapsed aria-expanded="false" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button" 
	        span.sr-only Toggle navigation
	        span.icon-bar
	        span.icon-bar
	        span.icon-bar
      	/ a.navbar-brand href="#"  Brand
      	.subjects
      		ul
		      	li.dropdown
				    a.dropdown-toggle data-toggle="dropdown" href="#" 
				    	| Сферы
				    	span.caret
				    ul.dropdown-menu role="menu" 
						- @main_sections.each do |s|
							li.main_field_link
								= link_to s.name, s
								/ - unless Section.where(parent_section_id: s.id).empty?
								/ 	ul.sub_link
								/ 		- Section.where(parent_section_id: s.id).each do |m|
								/ 			li.sub 
								/ 				= link_to m.name, m
				li.dropdown
				    a.dropdown-toggle data-toggle="dropdown" href="#" 
				    	| Индустрии
				    	span.caret
				    ul.dropdown-menu role="menu" 

						- Field.all.each do |f|
							li.main_field_link
								= link_to f.name, f
								/ - unless Section.where(parent_section_id: s.id).empty?
								/ 	ul.sub_link
								/ 		- Section.where(parent_section_id: s.id).each do |m|
								/ 			li.sub 
								/ 				= link_to m.name, m

				li
					= link_to "Лента", layouts_path
				li 
					= link_to(image_tag("users_black.png", class: "users_icon"), users_path)
		
		.logo_wrap.center
			= link_to(image_tag("logo.png", class: "top_logo"), root_path)
		.user_wrap
			- if current_user
				ul
					li.avatar
						= link_to(image_tag(current_user.image, class: "avatar"), current_user)
					li.name = link_to current_user.name, current_user
					li.out = link_to "Выйти", destroy_user_session_path, method: :delete
			- else
				ul
					li.out Войти через
					li.fb
						= link_to(image_tag('fb-icon.png', class: "fb-small"), user_facebook_omniauth_authorize_path)

   
    /! Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          	= link_to "Лента", layouts_path
            / | Link
            / span.sr-only (current)
        / li
        /   a href="#"  Link
        li.dropdown
          a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            | Сферы
            span.caret
          ul.dropdown-menu
          	- @main_sections.each do |s|
				li.main_field_link
					= link_to s.name, s
					/ - unless Section.where(parent_section_id: s.id).empty?
					/ 	ul.sub_link
					/ 		- Section.where(parent_section_id: s.id).each do |m|
					/ 			li.sub 
					/ 				= link_to m.name, m
		li.dropdown
          	a.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
            	| Индустрии
				span.caret
		    ul.dropdown-menu role="menu" 

				- Field.all.each do |f|
					li.main_field_link
						= link_to f.name, f
		li
			= link_to "Все пользователи", users_path
		
		- if current_user
			li.out_mobile
				= link_to "Выйти", destroy_user_session_path, method: :delete

          	

app/views/layouts/application.html.slim
doctype html
html[lang="ru"]
    head
        title
            | Mindy
        meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        = favicon_link_tag 'favicon.ico'
        = csrf_meta_tags
        / = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
        / = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
        
        = stylesheet_link_tag    'application', media: 'all'
        
        = javascript_include_tag 'application', 'medium-editor.js', 'sticky-kit.js'
        
        = render 'favicon'
        = display_meta_tags
        meta(http-equiv="X-UA-Compatible" content="IE=edge,chrome=1")
        == render 'layouts/google_analytics'
        

    body
        = render 'layouts/top_menu'
        .notice
            = notice
        .alert
            = alert
        = yield
        = render 'layouts/footer' unless @disable_footer
        |<script src="//yastatic.net/es5-shims/0.0.2/es5-shims.min.js"></script>
        |<script src="//yastatic.net/share2/share.js"></script>

  

app/views/layouts/edit.html.slim
.main_body
	- if current_user == @layout.user

		= simple_form_for @layout, html: { class: 'form-horizontal'  } do |f|
			.l_sidebar
				.text_block
					.input.dropdown_bold
						= f.association :section, as: :select, collection: Section.all, prompt: "Сфера", label: false
					.input.dropdown_bold
						= f.association :field, as: :select, collection: Field.all, prompt: "Индустрия", label: false
				
					.input_layout_name
						= f.input :name, placeholder: 'Название макета...', label: false, :input_html => { class: 'input-name' }
					.input
						= f.input :description, label: false, placeholder: 'Краткое описание, что макет помогает считать или анализировать...', :input_html => { class: 'input-description' }
						/ =f.hidden_field :section_id, :value => @layout.section_id

					
			.r_main_wrap
				.layout_body
					.input_layout_content
						= f.input :heading, label: false, placeholder: 'Заголовок...', :input_html => { class: 'input-heading'} 

					.input_layout_content
						= f.input :content, label: false, placeholder: 'Раскройте суть методологии...', :input_html => { class: 'input-content' }, as: :wysihtml5

						= f.button :submit, "Сохранить", class: "btn btn-default", id: "trigger"
					

app/views/layouts/index.html.slim
/ - @disable_footer = true
.big_wrap
	.container
		- if current_user
			.row
				.col-md-12
					.layouts_group
							.button_add_layout
								= link_to "Поделиться знанием", new_layout_path, class: 'btn btn-default'
		.row
			.col-md-12
				.latest_updates.profile
					| Вся лента:
				
				.small_sections_wrap.main_page
					= render @layouts

app/views/layouts/new.html.slim
- @disable_footer = true
.main_body
	= simple_form_for @layout, html: { class: 'form-horizontal'  } do |f|
		div id="main"
			.l_sidebar.edit
				.text_block
					
					.input.dropdown_bold
						= f.association :section, as: :select, collection: Section.all, prompt: "Выберите сферу", label: false
					.input.dropdown_bold
						= f.association :field, as: :select, collection: Field.all, prompt: "Выберите индустрию", label: false
					br
					
				
					.input_layout_name
						= f.input :name, placeholder: 'Название...', label: false, :input_html => { class: 'input-name' }
					.input
						= f.input :description, label: false, placeholder: 'Кратко о том, что статья помогает считать или анализировать...', :input_html => { class: 'input-description' }
					

		div id="right"		
				
			.r_main_wrap
				.layout_body
					.hint
						| Редактор текста появляется при выделении слов. Woohoo

					.input_layout_content
						= f.input :heading, label: false, placeholder: 'Заголовок...', :input_html => { class: 'input-heading'} 

					.input_layout_content
						
						/ = f.input :content, label: false, placeholder: 'Раскройте суть...', :input_html => { class: 'input-content' }, as: :wysihtml5
							
						= f.input :content, label: false, placeholder: 'Раскройте суть...', :input_html => { class: 'editable' }


					.publish

						= f.button :submit, "Опубликовать", class: "btn btn-default", id: "trigger"
					

app/views/layouts/show.html.slim
- @disable_footer = true
.main_body
	div id="main"
		.l_sidebar
		
			.text_block

				.back_wrap_layout
					= link_to image_tag('back_icon.png', class: "back_icon") + @layout.section.name, @layout.section
			
				.layout_name_holder
					= @layout.name
				.layout_description_holder
					= @layout.description

	div id="right"		
		.r_main_wrap
			.layout_body
				- if current_user == @layout.user
					.edit_button
						= link_to(image_tag("edit.png", class: "edit_icon"), edit_layout_path(@layout))
						= link_to(image_tag("delete_article.png", class: "edit_icon"), layout_path(@layout), method: :delete)

						
				.layout_heading_holder
					= @layout.heading



				.layout_content_holder
					= raw safe @layout.content

			.social_share_wrap
				.ya-share2 data-services="vkontakte,facebook,linkedin" data-description='#{@layout.description}' data-image='#{@layout.user.image}' data-title='#{@layout.name}'
				
			.comments_separator
				.comments_wrap
					.post__body
						.add-post__avatar
							.avatar-wrap.comments
								= link_to(image_tag(current_user.image, class: "avatar"), current_user)

						.add-post__body#first-tab-group.tabgroup
							.add-post__tab#news
								= simple_form_for(@comment) do |f| 
								    .input_comment
								        = f.input :content, placeholder: 'Ваш комментарий...', label: false, :input_html => { class: 'input-comment' }
								        = f.input :layout_id, :as => :hidden, :input_html => { :value => @layout.id }
								        .right
								            = f.submit "Добавить", class: "orange_btn"
								
				
					.comments_made
						- @layout.comments.reverse.each do |comment|
							.layout_card_wrap
								.avatar-wrap
									= link_to (image_tag comment.user.image, class: 'avatar'), comment.user
								.author__description
									.author__name
										= link_to comment.user.name, comment.user
										
									.post__time_s
										= time_ago_in_words(comment.user.created_at) + ' назад'
										
								.layout_card_description.comment
									= comment.content
					
								